[build]
install = 'npm install && npx prisma generate --schema=server/prisma/schema.prisma'

[phases.setup]
nixPkgs = ['nodejs', 'openssl']

[start]
cmd = 'npx prisma migrate deploy --schema=server/prisma/schema.prisma && npm start --workspace=server'
