[build]
install = 'npm install && npx prisma generate --schema=server/prisma/schema.prisma'

[phases.setup]
nixPkgs = ['nodejs', 'openssl']

[start]
cmd = 'npx prisma db push --schema=server/prisma/schema.prisma --accept-data-loss && node server/src/app.js'
